version: "3"

services:
  backend:
    container_name: server
    build: server
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongo
    expose: 
        - 27017
    ports:
      - 27017:27017
  mongo_auth:
    build: ./mongo_auth
    depends_on:
        - mongodb
  frontend:
    container_name: client
    build: client
    ports:
      - "3001:3001"